# output: github_document
output: 
  pdf_document:
    keep_tex: true
    fig_caption: true
    latex_engine: pdflatex
    template: svm-latex-ms.tex
    number_sections: true
title: | 
        | Mi playa
        | Subtítulo
        | Subtítulo
author:
- name: Carolain Pérez Ureña
  affiliation: Estudiante, Universidad Autónoma de Santo Domingo (UASD)
abstract: "En este trabajo se ha estudiado la transformación de la linea costera en playa Najayo, San Cristóbal sur de República Dominicana analizando imágenes satelitales de años anteriores y comparándolas con imágenes aéreas actuales. Para ello, se examinaron las fotos de los últimos 30 años  para ver evidencia del cambio en el trazado de la linea. Los fenomenos atmosfericos, crecida del nivel del mar y la actividad humana han sido los factores determinantes en dicho cambio."

keywords: "línea de costa, Najayo, beachrock, satelitales,"
date: "`r format(Sys.time(), '%B %d, %Y')`"
geometry: margin=1in
fontfamily: mathpazo
fontsize: 11pt
# spacing: double
bibliography: bibliography.bib 


# csl: plos-one.csl
csl: apa.csl
header-includes:
  \usepackage{pdflscape}
  \newcommand{\blandscape}{\begin{landscape}}
  \newcommand{\elandscape}{\end{landscape}}
---

# Introducción

La playa es la zona donde se depositan y se acumulan sedimentos arrastrados principalmente por las olas. Estos sedimentos pueden ser finos o gruesos. Es fundamental que la acumulación de material sea mayor que la erosión en el litoral costero para la formación de una playa, así como su área geomórfologica.

La compactación de los materiales da lugar al *beachrock* o roca de playa, la cual es una roca sedimentaria friable bien cementada que consiste en una mezcla variable de sedimento de grava, arena y limo cementada con minerales de carbonato. El carbonato de calcio se encarga de fosilizar el *beachrock*, dando lugar a playas rocosas. Dependiendo de la ubicación, el sedimento puede consistir en una mezcla variable de conchas, fragmentos de coral, fragmentos de roca de diferentes tipos y otros materiales [@jackson2005glossary]. 

En las costas en retirada, los afloramientos de roca de playa pueden ser evidentes en alta mar donde actuan como una barrera contra la erosión costera. La presencia de roca de playa también puede inducir deficiencia de sedimento en una playa y sincronizar su régimen de olas (bibliografía). 

La costa es la franja de tierra que tiene contacto e interaccion con el medio acuático. Por tanto es en esta parte de la playa donde más cambios se registran, tanto a escala geológica como histórica ancestral y reciente. El origen de estas transformaciones es principalemnte la oscilación de aguas marinas @pedraza1996geomorfologia.Los efectos de estas alteraciones se traducen en un retroceso acelerado de la costa, que se evidencia atraves de registro de imágenes aéreas, las cuales se analizan para dar seguimiento a los cambios ocurridos en las costas @ortiz1992retroceso.

La confluencia entre la zona marina y la terrestre produce unos fenómenos que tienden a afectar las costas, conocidos como procesos físicos litorales. Entre estos se distinguen los de tipo marítimo (oleaje, corrientes, mareas) geológios (tsunamis), climáticos (vientos, huracanes) y continentales (erosión hídrica y depósito de sedimentos fluviales) (bibliografía).

Los cambios más significativos son producidos por la crecida del nivel del mar en los últimos 19,000 años, así como por la presión de las olas que provoca el desgaste y sedimentación en las costas. Esta acción hidráulica provoca una modelación fisiográfica, que según @pedraza1996geomorfologia puede dar lugar a distintos tipos de costas como por ejemplo de ría, de fiordo, de cala, de isla barrera, arenosas o playas estabilizadas, de delta entre otras. Por otra parte, según su dinámica, las costas se clasifican en "de progradación", estacionaria y "de retrogradación" [@codignotto1997geomorfologia].

Dada estas características dinámicas que alteran la morfología litoral, es importante estudiar su geomorfología, ya que permite analizar las modificaciones a escala histórica. El presente estudio realizado en la playa Najayo conocida localmente como "playa los pescadores" se ubica en la provincia San Cristóbal, en la región administrativa de Valdesia, sur de Republica Dominicana. Su formación datan de la era Cenozoica. La playa de Najayo sufre cambios significativos que se evidencian a lo largo de los años, uno de estos y en el que se basa este estudio es el fenómeno de retrogradación en la linea costera por erosión.


\ldots

# Metodología

Los métodos de análisis fueron variados. Comenzamos a marcar con aerosol siete puntos en orden numerico a lo largo de la playa, luego se utilizó un teodolito con un GPS para obtener las coordenadas exactas de los lugares marcados. Por otra parte la recoleción de sedimentos en forma de muestra es propicio para la comparación de la variación del tamaño de rocas según la ubicación. Las muestras recogidas fueron en cuatro puntos diferentes de la playa, una en cada extremo, indentificados como frente de Duna occidental y frente de Duna oriental, una en la berna de la Duna y otra en frente del Antiguo Canal,(mapa) del arroyo Rolón.

Con la aplicación ODK Collection se completa un formularió con los datos referentes a la ubicación.

Las imagenes satelitales se usaron para la detección de cambios ocurridos entre años pasados y la actulidad. De esta manera fueron tomadas imágenes aereas por un Dron que cubrieron toda el área de costa, las cuales han sido comparadas con imagenes satelitales con hechas a partir de landast 8 entre los años 2013 a 2019. Para llevar a cabo el analisis de las modificaciones, fue necesario delimitar la linea de la costa de la playa. Estas demarcaciones fueron hechas en Qgis. A medida que el trazado se encuentre más lejos de su punto de inicio, se entiende una retrogradacion de la costa. (mapa del traza de la linea)



La playa "los pescadores" se trata de una playa con un perfil de acantilado y un rango de marea muy estrecha, es decir, que la linea de costa no cambia mucho de acuerdo a los ciclos de marea.La modificacion del litoral costero se produce por a partir de fenomenos significativos. litológicamente está compuesta por  arena y gravas bioclasticas formando el cordón litoral, en el fondo de valle coglomerado, gravas, arenas, calizas arrecifal, calciruditas y calcarenitas de acuerdo con el mapa geológico Nacional. El *beachrock* de la playa está compuesto por basalto, fósiles arrastrados, rocas alteradas, tonalitas, calizas, rocas intrusivas fosilizada por carbonato de calcio usual en la región sur de la Republica Dominicana y propio del periodo pleistoceno @mapa_geologogico_250k_rect_resolucion_media.tif 


Entre su vegetacion se encuentra;

@Almendra.jpeg




Empleamos el método de  transectos lineales, que ha sido utilizado para estimar la distancia que hay entre una linea de costa cualquiera hasta la linea de costa de referencia a partir de la cual muestra si se hay evidencia de retrogradación, progradación o por defecto estacionariddad en un lapso. En la interseccion entre el transecto y cada linea que tiene asociada se forma un punto que contiene un valor de fecha.



\ldots

# Resultados
Los resultados arrojaron lo siguiente 


\ldots

# Discusión

# Agradecimientos

# Información de soporte

\ldots

# *Script* reproducible

\ldots

# Referencias

